### ISSUE TITLE
Custom errors for each key

### ISSUE THREAD

**Issue by thngdude** [eddyystop/feathers-hooks-validate-joi#10]
Are custom error messages for each key supported?

I tried the following as per the documentation for joi, but it seems to continue to throw a generic "Bad Request: Invalid Data" message:
```
const Firstname = Joi.string().trim().min(3).max(50).alphanum().required().error(() => "Firstname is invalid");
```
I also tried this:
```
const Firstname = Joi.string().trim().min(3).max(50).alphanum().required().error(new Error( "Firstname is invalid"));
```

Both of the above were validated against "s", with the same "Invalid Data" error message as a result.

**Comment by eddyystop** [comment]
Sorry I haven't had to use custom errors with Joi.

**Comment by thngdude** [comment]
Does that mean no?

**Comment by thngdude** [comment]
If it doesn't support individual custom errors for each key, can you advise whether it would at least have a generic message for each key with different options/code?

It would be difficult to advise a user on what to change in a form input based on "Invalid Data".

**Comment by eddyystop** [comment]
I believe Joi has a chained method which specifies a custom message for a validation. Dig into the docs.

**Comment by eddyystop** [comment]
From memory, isn't it supposed to be `.error('My custom message')`
